---
- name: Pull docker image of caldevops
  hosts: all
  tasks:
    - name: Pull caldevops devops image
      docker_image:
        name: zaindol/caldevops
        source: pull

- name: Run Docker Image
  hosts: all
  tasks:
    - name: deploy caldevops docker container
      docker_container:
        image: zaindol/caldevops
        name: caldevops
        state: started
        auto_remove: true
        ports:
          - "3000:3000"
...